In [1]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
import sqlite3


# Importing the dataset
conn = sqlite3.connect('database.sqlite')

In [2]:
cursor = conn.cursor()

In [3]:
cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")
print(cursor.fetchall())

[('sqlite_sequence',), ('Player_Attributes',), ('Player',), ('Match',), ('League',), ('Country',), ('Team',), ('Team_Attributes',)]

In [4]:
df_league = pd.read_sql_query("select * from League;", conn)
df_league.head()

      id  country_id                    name
0      1           1  Belgium Jupiler League
1   1729        1729  England Premier League
2   4769        4769          France Ligue 1
3   7809        7809   Germany 1. Bundesliga
4  10257       10257           Italy Serie A

In [5]:
df_player_attributes = pd.read_sql_query("select * from Player_Attributes;", conn)
df_player = pd.read_sql_query("select * from Player;", conn)
df_match = pd.read_sql_query("select * from Match;", conn)
df_country = pd.read_sql_query("select * from Country;", conn)
df_team_attributes = pd.read_sql_query("select * from Team_Attributes;", conn)
df_team = pd.read_sql_query("select * from Team;", conn)

In [6]:
df_player_attributes.head()

,id,player_fifa_api_id,player_api_id,date,overall_rating,potential,preferred_foot,attacking_work_rate,defensive_work_rate,crossing,...,vision,penalties,marking,standing_tackle,sliding_tackle,gk_diving,gk_handling,gk_kicking,gk_positioning,gk_reflexes
0,1,218353,505942,2016-02-18 00:00:00,67.0,71.0,right,medium,medium,49.0,...,54.0,48.0,65.0,69.0,69.0,6.0,11.0,10.0,8.0,8.0
1,2,218353,505942,2015-11-19 00:00:00,67.0,71.0,right,medium,medium,49.0,...,54.0,48.0,65.0,69.0,69.0,6.0,11.0,10.0,8.0,8.0
2,3,218353,505942,2015-09-21 00:00:00,62.0,66.0,right,medium,medium,49.0,...,54.0,48.0,65.0,66.0,69.0,6.0,11.0,10.0,8.0,8.0
3,4,218353,505942,2015-03-20 00:00:00,61.0,65.0,right,medium,medium,48.0,...,53.0,47.0,62.0,63.0,66.0,5.0,10.0,9.0,7.0,7.0
4,5,218353,505942,2007-02-22 00:00:00,61.0,65.0,right,medium,medium,48.0,...,53.0,47.0,62.0,63.0,66.0,5.0,10.0,9.0,7.0,7.0

In [7]:
df_player.head()

,id,player_api_id,player_name,player_fifa_api_id,birthday,height,weight
0,1,505942,Aaron Appindangoye,218353,1992-02-29 00:00:00,182.88,187
1,2,155782,Aaron Cresswell,189615,1989-12-15 00:00:00,170.18,146
2,3,162549,Aaron Doran,186170,1991-05-13 00:00:00,170.18,163
3,4,30572,Aaron Galindo,140161,1982-05-08 00:00:00,182.88,198
4,5,23780,Aaron Hughes,17725,1979-11-08 00:00:00,182.88,154

In [8]:
df_country.head()

      id     name
0      1  Belgium
1   1729  England
2   4769   France
3   7809  Germany
4  10257    Italy

In [9]:
df_team_attributes.head()

,id,team_fifa_api_id,team_api_id,date,buildUpPlaySpeed,buildUpPlaySpeedClass,buildUpPlayDribbling,buildUpPlayDribblingClass,buildUpPlayPassing,buildUpPlayPassingClass,...,chanceCreationShooting,chanceCreationShootingClass,chanceCreationPositioningClass,defencePressure,defencePressureClass,defenceAggression,defenceAggressionClass,defenceTeamWidth,defenceTeamWidthClass,defenceDefenderLineClass
0,1,434,9930,2010-02-22 00:00:00,60,Balanced,NaN,Little,50,Mixed,...,55,Normal,Organised,50,Medium,55,Press,45,Normal,Cover
1,2,434,9930,2014-09-19 00:00:00,52,Balanced,48.0,Normal,56,Mixed,...,64,Normal,Organised,47,Medium,44,Press,54,Normal,Cover
2,3,434,9930,2015-09-10 00:00:00,47,Balanced,41.0,Normal,54,Mixed,...,64,Normal,Organised,47,Medium,44,Press,54,Normal,Cover
3,4,77,8485,2010-02-22 00:00:00,70,Fast,NaN,Little,70,Long,...,70,Lots,Organised,60,Medium,70,Double,70,Wide,Cover
4,5,77,8485,2011-02-22 00:00:00,47,Balanced,NaN,Little,52,Mixed,...,52,Normal,Organised,47,Medium,47,Press,52,Normal,Cover

In [10]:
df_team.head()

   id  team_api_id  team_fifa_api_id     team_long_name team_short_name
0   1         9987             673.0           KRC Genk             GEN
1   2         9993             675.0       Beerschot AC             BAC
2   3        10000           15005.0   SV Zulte-Waregem             ZUL
3   4         9994            2007.0   Sporting Lokeren             LOK
4   5         9984            1750.0  KSV Cercle Brugge             CEB

In [11]:
df_match.head()

,id,country_id,league_id,season,stage,date,match_api_id,home_team_api_id,away_team_api_id,home_team_goal,...,SJA,VCH,VCD,VCA,GBH,GBD,GBA,BSH,BSD,BSA
0,1,1,1,2008/2009,1,2008-08-17 00:00:00,492473,9987,9993,1,...,4.00,1.65,3.40,4.50,1.78,3.25,4.00,1.73,3.40,4.20
1,2,1,1,2008/2009,1,2008-08-16 00:00:00,492474,10000,9994,0,...,3.80,2.00,3.25,3.25,1.85,3.25,3.75,1.91,3.25,3.60
2,3,1,1,2008/2009,1,2008-08-16 00:00:00,492475,9984,8635,0,...,2.50,2.35,3.25,2.65,2.50,3.20,2.50,2.30,3.20,2.75
3,4,1,1,2008/2009,1,2008-08-17 00:00:00,492476,9991,9998,5,...,7.50,1.45,3.75,6.50,1.50,3.75,5.50,1.44,3.75,6.50
4,5,1,1,2008/2009,1,2008-08-16 00:00:00,492477,7947,9985,1,...,1.73,4.50,3.40,1.65,4.50,3.50,1.65,4.75,3.30,1.67

In [12]:
df_country.head()

      id     name
0      1  Belgium
1   1729  England
2   4769   France
3   7809  Germany
4  10257    Italy

In [13]:
df_match.isna().sum()

id                      0
country_id              0
league_id               0
season                  0
stage                   0
date                    0
match_api_id            0
home_team_api_id        0
away_team_api_id        0
home_team_goal          0
away_team_goal          0
home_player_X1       1821
home_player_X2       1821
home_player_X3       1832
home_player_X4       1832
home_player_X5       1832
home_player_X6       1832
home_player_X7       1832
home_player_X8       1832
home_player_X9       1832
home_player_X10      1832
home_player_X11      1832
away_player_X1       1832
away_player_X2       1832
away_player_X3       1832
away_player_X4       1832
away_player_X5       1832
away_player_X6       1832
away_player_X7       1832
away_player_X8       1832
                    ...
B365H                3387
B365D                3387
B365A                3387
BWH                  3404
BWD                  3404
BWA                  3404
IWH                  3459
IWD                  3459
IWA                  3459
LBH                  3423
LBD                  3423
LBA                  3423
PSH                 14811
PSD                 14811
PSA                 14811
WHH                  3408
WHD                  3408
WHA                  3408
SJH                  8882
SJD                  8882
SJA                  8882
VCH                  3411
VCD                  3411
VCA                  3411
GBH                 11817
GBD                 11817
GBA                 11817
BSH                 11818
BSD                 11818
BSA                 11818
Length: 115, dtype: int64

In [14]:
df_team_attributes.isna().sum()

id                                  0
team_fifa_api_id                    0
team_api_id                         0
date                                0
buildUpPlaySpeed                    0
buildUpPlaySpeedClass               0
buildUpPlayDribbling              969
buildUpPlayDribblingClass           0
buildUpPlayPassing                  0
buildUpPlayPassingClass             0
buildUpPlayPositioningClass         0
chanceCreationPassing               0
chanceCreationPassingClass          0
chanceCreationCrossing              0
chanceCreationCrossingClass         0
chanceCreationShooting              0
chanceCreationShootingClass         0
chanceCreationPositioningClass      0
defencePressure                     0
defencePressureClass                0
defenceAggression                   0
defenceAggressionClass              0
defenceTeamWidth                    0
defenceTeamWidthClass               0
defenceDefenderLineClass            0
dtype: int64

In [15]:
df_team.isna().sum()

id                   0
team_api_id          0
team_fifa_api_id    11
team_long_name       0
team_short_name      0
dtype: int64

In [16]:
df_player.isna().sum()

id                    0
player_api_id         0
player_name           0
player_fifa_api_id    0
birthday              0
height                0
weight                0
dtype: int64

In [17]:
df_player_attributes.isna().sum()

id                        0
player_fifa_api_id        0
player_api_id             0
date                      0
overall_rating          836
potential               836
preferred_foot          836
attacking_work_rate    3230
defensive_work_rate     836
crossing                836
finishing               836
heading_accuracy        836
short_passing           836
volleys                2713
dribbling               836
curve                  2713
free_kick_accuracy      836
long_passing            836
ball_control            836
acceleration            836
sprint_speed            836
agility                2713
reactions               836
balance                2713
shot_power              836
jumping                2713
stamina                 836
strength                836
long_shots              836
aggression              836
interceptions           836
positioning             836
vision                 2713
penalties               836
marking                 836
standing_tackle         836
sliding_tackle         2713
gk_diving               836
gk_handling             836
gk_kicking              836
gk_positioning          836
gk_reflexes             836
dtype: int64

In [18]:
df_player_attributes.head()

,id,player_fifa_api_id,player_api_id,date,overall_rating,potential,preferred_foot,attacking_work_rate,defensive_work_rate,crossing,...,vision,penalties,marking,standing_tackle,sliding_tackle,gk_diving,gk_handling,gk_kicking,gk_positioning,gk_reflexes
0,1,218353,505942,2016-02-18 00:00:00,67.0,71.0,right,medium,medium,49.0,...,54.0,48.0,65.0,69.0,69.0,6.0,11.0,10.0,8.0,8.0
1,2,218353,505942,2015-11-19 00:00:00,67.0,71.0,right,medium,medium,49.0,...,54.0,48.0,65.0,69.0,69.0,6.0,11.0,10.0,8.0,8.0
2,3,218353,505942,2015-09-21 00:00:00,62.0,66.0,right,medium,medium,49.0,...,54.0,48.0,65.0,66.0,69.0,6.0,11.0,10.0,8.0,8.0
3,4,218353,505942,2015-03-20 00:00:00,61.0,65.0,right,medium,medium,48.0,...,53.0,47.0,62.0,63.0,66.0,5.0,10.0,9.0,7.0,7.0
4,5,218353,505942,2007-02-22 00:00:00,61.0,65.0,right,medium,medium,48.0,...,53.0,47.0,62.0,63.0,66.0,5.0,10.0,9.0,7.0,7.0

# Finding similar players

In [19]:
df_player.drop('id',inplace=True,axis=1)
df_player.head()

,player_api_id,player_name,player_fifa_api_id,birthday,height,weight
0,505942,Aaron Appindangoye,218353,1992-02-29 00:00:00,182.88,187
1,155782,Aaron Cresswell,189615,1989-12-15 00:00:00,170.18,146
2,162549,Aaron Doran,186170,1991-05-13 00:00:00,170.18,163
3,30572,Aaron Galindo,140161,1982-05-08 00:00:00,182.88,198
4,23780,Aaron Hughes,17725,1979-11-08 00:00:00,182.88,154

In [20]:
#df_player_attributes.drop('id',inplace=True,axis=1)
df_player_attributes.head()

,id,player_fifa_api_id,player_api_id,date,overall_rating,potential,preferred_foot,attacking_work_rate,defensive_work_rate,crossing,...,vision,penalties,marking,standing_tackle,sliding_tackle,gk_diving,gk_handling,gk_kicking,gk_positioning,gk_reflexes
0,1,218353,505942,2016-02-18 00:00:00,67.0,71.0,right,medium,medium,49.0,...,54.0,48.0,65.0,69.0,69.0,6.0,11.0,10.0,8.0,8.0
1,2,218353,505942,2015-11-19 00:00:00,67.0,71.0,right,medium,medium,49.0,...,54.0,48.0,65.0,69.0,69.0,6.0,11.0,10.0,8.0,8.0
2,3,218353,505942,2015-09-21 00:00:00,62.0,66.0,right,medium,medium,49.0,...,54.0,48.0,65.0,66.0,69.0,6.0,11.0,10.0,8.0,8.0
3,4,218353,505942,2015-03-20 00:00:00,61.0,65.0,right,medium,medium,48.0,...,53.0,47.0,62.0,63.0,66.0,5.0,10.0,9.0,7.0,7.0
4,5,218353,505942,2007-02-22 00:00:00,61.0,65.0,right,medium,medium,48.0,...,53.0,47.0,62.0,63.0,66.0,5.0,10.0,9.0,7.0,7.0

## Combining two tables

In [21]:
df_comb_player =  df_player_attributes

In [22]:
df_comb_player.head()

,id,player_fifa_api_id,player_api_id,date,overall_rating,potential,preferred_foot,attacking_work_rate,defensive_work_rate,crossing,...,vision,penalties,marking,standing_tackle,sliding_tackle,gk_diving,gk_handling,gk_kicking,gk_positioning,gk_reflexes
0,1,218353,505942,2016-02-18 00:00:00,67.0,71.0,right,medium,medium,49.0,...,54.0,48.0,65.0,69.0,69.0,6.0,11.0,10.0,8.0,8.0
1,2,218353,505942,2015-11-19 00:00:00,67.0,71.0,right,medium,medium,49.0,...,54.0,48.0,65.0,69.0,69.0,6.0,11.0,10.0,8.0,8.0
2,3,218353,505942,2015-09-21 00:00:00,62.0,66.0,right,medium,medium,49.0,...,54.0,48.0,65.0,66.0,69.0,6.0,11.0,10.0,8.0,8.0
3,4,218353,505942,2015-03-20 00:00:00,61.0,65.0,right,medium,medium,48.0,...,53.0,47.0,62.0,63.0,66.0,5.0,10.0,9.0,7.0,7.0
4,5,218353,505942,2007-02-22 00:00:00,61.0,65.0,right,medium,medium,48.0,...,53.0,47.0,62.0,63.0,66.0,5.0,10.0,9.0,7.0,7.0

In [23]:
import datetime as dt
df_comb_player['date'] = pd.to_datetime(df_comb_player['date'])

# Finding Top Players

In [24]:
df_comb_player_2016 = df_comb_player[df_comb_player['date'].dt.year == 2016]
df_comb_player_2016 = df_comb_player_2016.sort_values('date').groupby('player_api_id').last()
df_comb_player_2016.sort_values('overall_rating').tail(10)

,id,player_fifa_api_id,date,overall_rating,potential,preferred_foot,attacking_work_rate,defensive_work_rate,crossing,finishing,...,vision,penalties,marking,standing_tackle,sliding_tackle,gk_diving,gk_handling,gk_kicking,gk_positioning,gk_reflexes
player_api_id,,,,,,,,,,,,,,,,,,,,,
30894,143229,121939,2016-01-28,87.0,87.0,right,medium,high,84.0,47.0,...,83.0,71.0,86.0,87.0,95.0,11.0,12.0,5.0,14.0,5.0
182917,39201,193080,2016-04-21,87.0,90.0,right,medium,medium,17.0,13.0,...,68.0,40.0,13.0,21.0,13.0,88.0,81.0,86.0,85.0,89.0
164684,76431,198710,2016-02-18,87.0,93.0,left,medium,medium,88.0,85.0,...,87.0,81.0,25.0,47.0,30.0,15.0,15.0,15.0,5.0,14.0
36378,122442,176635,2016-02-18,88.0,89.0,left,medium,low,80.0,75.0,...,93.0,76.0,22.0,16.0,19.0,6.0,14.0,10.0,6.0,14.0
107417,47248,183277,2016-01-28,88.0,90.0,right,high,medium,80.0,81.0,...,86.0,86.0,25.0,27.0,22.0,11.0,12.0,6.0,8.0,8.0
93447,150542,188545,2016-01-28,88.0,89.0,right,medium,medium,62.0,89.0,...,78.0,77.0,25.0,42.0,19.0,15.0,6.0,12.0,8.0,10.0
37412,160836,153079,2016-03-10,88.0,88.0,right,high,medium,70.0,90.0,...,83.0,83.0,13.0,20.0,12.0,13.0,15.0,6.0,11.0,14.0
30834,16461,9014,2016-01-28,89.0,89.0,left,high,low,80.0,85.0,...,84.0,80.0,29.0,26.0,26.0,10.0,8.0,11.0,5.0,15.0
27299,109034,167495,2016-04-21,90.0,90.0,right,medium,medium,15.0,13.0,...,70.0,37.0,10.0,10.0,11.0,85.0,87.0,91.0,90.0,87.0
19533,131465,190871,2016-02-04,90.0,94.0,right,high,medium,72.0,88.0,...,79.0,81.0,21.0,24.0,33.0,9.0,9.0,15.0,15.0,11.0

In [25]:
df_comb_player_2015 = df_comb_player[df_comb_player['date'].dt.year == 2015]
df_comb_player_2015 = df_comb_player_2015.sort_values('date').groupby('player_api_id').last()
df_comb_player_2015.sort_values('overall_rating').tail(10)

,id,player_fifa_api_id,date,overall_rating,potential,preferred_foot,attacking_work_rate,defensive_work_rate,crossing,finishing,...,vision,penalties,marking,standing_tackle,sliding_tackle,gk_diving,gk_handling,gk_kicking,gk_positioning,gk_reflexes
player_api_id,,,,,,,,,,,,,,,,,,,,,
37459,40431,168542,2015-09-21,88.0,88.0,left,high,low,85.0,72.0,...,93.0,77.0,23.0,30.0,29.0,1.0,1.0,1.0,1.0,1.0
30955,12774,41,2015-10-16,88.0,88.0,right,high,medium,79.0,73.0,...,92.0,71.0,57.0,57.0,56.0,6.0,13.0,6.0,13.0,7.0
19533,131467,190871,2015-12-03,89.0,94.0,right,high,medium,72.0,87.0,...,79.0,81.0,21.0,24.0,33.0,9.0,9.0,15.0,15.0,11.0
35724,183673,41236,2015-09-21,89.0,89.0,right,medium,low,76.0,90.0,...,83.0,91.0,15.0,41.0,27.0,13.0,15.0,10.0,9.0,12.0
107417,47249,183277,2015-09-25,89.0,91.0,right,high,medium,80.0,83.0,...,86.0,86.0,25.0,27.0,22.0,11.0,12.0,6.0,8.0,8.0
30834,16462,9014,2015-09-25,90.0,90.0,left,high,low,80.0,85.0,...,84.0,80.0,29.0,26.0,26.0,10.0,8.0,11.0,5.0,15.0
27299,109037,167495,2015-11-26,90.0,90.0,right,medium,medium,15.0,13.0,...,70.0,37.0,10.0,10.0,11.0,85.0,87.0,91.0,90.0,87.0
40636,105984,176580,2015-10-16,90.0,90.0,right,high,medium,77.0,90.0,...,84.0,85.0,30.0,45.0,38.0,27.0,25.0,31.0,33.0,37.0
30893,33331,20801,2015-10-16,93.0,93.0,right,high,low,82.0,95.0,...,81.0,85.0,22.0,31.0,23.0,7.0,11.0,15.0,14.0,11.0
30981,102483,158023,2015-12-17,94.0,94.0,left,medium,low,80.0,93.0,...,90.0,74.0,13.0,23.0,21.0,6.0,11.0,15.0,14.0,8.0

In [26]:
df_comb_player_2014 = df_comb_player[df_comb_player['date'].dt.year == 2014]
df_comb_player_2014 = df_comb_player_2014.sort_values('date').groupby('player_api_id').last()
df_comb_player_2014.sort_values('overall_rating').tail(10)

,id,player_fifa_api_id,date,overall_rating,potential,preferred_foot,attacking_work_rate,defensive_work_rate,crossing,finishing,...,vision,penalties,marking,standing_tackle,sliding_tackle,gk_diving,gk_handling,gk_kicking,gk_positioning,gk_reflexes
player_api_id,,,,,,,,,,,,,,,,,,,,,
107417,47254,183277,2014-10-10,88.0,90.0,right,high,medium,78.0,83.0,...,86.0,86.0,25.0,27.0,22.0,11.0,12.0,6.0,8.0,8.0
22543,144922,167397,2014-09-18,88.0,88.0,right,high,medium,55.0,91.0,...,68.0,87.0,25.0,42.0,25.0,10.0,13.0,6.0,9.0,5.0
30872,19619,121944,2014-10-17,88.0,88.0,right,high,high,81.0,76.0,...,86.0,81.0,69.0,80.0,77.0,14.0,14.0,13.0,13.0,11.0
30955,12776,41,2014-11-07,89.0,89.0,right,high,medium,85.0,73.0,...,93.0,71.0,57.0,57.0,56.0,6.0,13.0,6.0,13.0,7.0
40636,105991,176580,2014-11-28,89.0,91.0,right,high,medium,77.0,91.0,...,84.0,85.0,30.0,45.0,38.0,27.0,25.0,31.0,33.0,37.0
27299,109042,167495,2014-09-18,90.0,90.0,right,medium,medium,25.0,25.0,...,20.0,37.0,25.0,25.0,25.0,87.0,85.0,92.0,90.0,86.0
30834,16465,9014,2014-10-17,90.0,90.0,left,high,low,80.0,85.0,...,84.0,80.0,29.0,26.0,26.0,10.0,8.0,11.0,5.0,15.0
35724,183675,41236,2014-10-17,90.0,90.0,right,medium,low,76.0,91.0,...,83.0,91.0,25.0,41.0,27.0,13.0,15.0,10.0,9.0,12.0
30893,33336,20801,2014-10-31,92.0,92.0,right,high,low,83.0,95.0,...,81.0,85.0,22.0,31.0,23.0,7.0,11.0,15.0,14.0,11.0
30981,102490,158023,2014-10-17,93.0,95.0,left,medium,low,84.0,94.0,...,90.0,76.0,25.0,21.0,20.0,6.0,11.0,15.0,14.0,8.0

In [27]:
df_comb_player_2013 = df_comb_player[df_comb_player['date'].dt.year == 2013]
df_comb_player_2013 = df_comb_player_2013.sort_values('date').groupby('player_api_id').last()
df_comb_player_2013.sort_values('overall_rating').tail(10)

,id,player_fifa_api_id,date,overall_rating,potential,preferred_foot,attacking_work_rate,defensive_work_rate,crossing,finishing,...,vision,penalties,marking,standing_tackle,sliding_tackle,gk_diving,gk_handling,gk_kicking,gk_positioning,gk_reflexes
player_api_id,,,,,,,,,,,,,,,,,,,,,
80562,169815,164240,2013-09-20,88.0,88.0,right,medium,high,60.0,38.0,...,74.0,71.0,91.0,91.0,88.0,9.0,12.0,5.0,9.0,10.0
30834,16470,9014,2013-09-27,88.0,88.0,left,high,low,80.0,83.0,...,82.0,79.0,29.0,24.0,25.0,10.0,8.0,11.0,5.0,15.0
30843,151478,7826,2013-09-20,89.0,89.0,left,high,low,83.0,91.0,...,82.0,89.0,23.0,32.0,21.0,9.0,10.0,5.0,7.0,8.0
39854,180718,10535,2013-09-20,89.0,89.0,right,medium,medium,85.0,74.0,...,96.0,75.0,55.0,61.0,61.0,5.0,15.0,12.0,5.0,9.0
30955,12780,41,2013-12-20,89.0,91.0,right,high,medium,85.0,73.0,...,93.0,65.0,57.0,57.0,56.0,6.0,13.0,6.0,13.0,7.0
35724,183679,41236,2013-09-27,89.0,89.0,right,medium,low,76.0,91.0,...,84.0,91.0,25.0,49.0,27.0,13.0,15.0,10.0,9.0,12.0
22543,144925,167397,2013-09-20,90.0,92.0,right,high,medium,55.0,94.0,...,68.0,87.0,25.0,42.0,25.0,10.0,13.0,6.0,9.0,5.0
30924,58698,156616,2013-11-29,90.0,90.0,right,high,medium,86.0,79.0,...,88.0,80.0,25.0,25.0,26.0,15.0,6.0,9.0,7.0,10.0
30893,33340,20801,2013-09-20,92.0,95.0,right,high,low,83.0,92.0,...,81.0,85.0,22.0,31.0,23.0,7.0,11.0,15.0,14.0,11.0
30981,102493,158023,2013-11-15,94.0,97.0,left,high,medium,84.0,97.0,...,90.0,76.0,25.0,21.0,20.0,6.0,11.0,15.0,14.0,8.0

In [28]:
df_comb_player_2012 = df_comb_player[df_comb_player['date'].dt.year == 2012]
df_comb_player_2012 = df_comb_player_2012.sort_values('date').groupby('player_api_id').last()
df_comb_player_2012.sort_values('overall_rating').tail(10)

,id,player_fifa_api_id,date,overall_rating,potential,preferred_foot,attacking_work_rate,defensive_work_rate,crossing,finishing,...,vision,penalties,marking,standing_tackle,sliding_tackle,gk_diving,gk_handling,gk_kicking,gk_positioning,gk_reflexes
player_api_id,,,,,,,,,,,,,,,,,,,,,
22543,144929,167397,2012-08-31,88.0,90.0,right,high,medium,55.0,91.0,...,54.0,87.0,16.0,42.0,19.0,10.0,13.0,6.0,9.0,5.0
37459,40445,168542,2012-08-31,88.0,91.0,left,high,low,81.0,78.0,...,91.0,77.0,23.0,30.0,29.0,13.0,9.0,13.0,9.0,13.0
30657,72603,5479,2012-08-31,89.0,90.0,left,medium,medium,13.0,9.0,...,32.0,24.0,11.0,11.0,9.0,91.0,83.0,69.0,85.0,92.0
30865,131142,140601,2012-08-31,89.0,89.0,right,medium,high,40.0,37.0,...,56.0,62.0,91.0,94.0,86.0,12.0,5.0,14.0,8.0,6.0
30829,178967,54050,2012-08-31,89.0,92.0,right,high,high,79.0,90.0,...,84.0,85.0,32.0,54.0,37.0,10.0,11.0,13.0,8.0,7.0
30924,58705,156616,2012-08-31,90.0,90.0,right,high,low,86.0,78.0,...,89.0,80.0,13.0,25.0,26.0,15.0,6.0,9.0,7.0,10.0
30955,12788,41,2012-08-31,90.0,93.0,right,high,medium,85.0,73.0,...,93.0,65.0,57.0,57.0,56.0,6.0,13.0,6.0,13.0,7.0
39854,180722,10535,2012-08-31,90.0,90.0,right,medium,medium,85.0,74.0,...,97.0,75.0,55.0,62.0,61.0,5.0,15.0,12.0,5.0,9.0
30893,33345,20801,2012-08-31,92.0,94.0,right,high,low,84.0,91.0,...,80.0,85.0,22.0,31.0,23.0,7.0,11.0,15.0,14.0,11.0
30981,102498,158023,2012-08-31,94.0,96.0,left,high,medium,85.0,95.0,...,90.0,76.0,13.0,21.0,20.0,6.0,11.0,15.0,14.0,8.0

In [29]:
df_comb_player_2011 = df_comb_player[df_comb_player['date'].dt.year == 2011]
df_comb_player_2011 = df_comb_player_2011.sort_values('date').groupby('player_api_id').last()
df_comb_player_2011.sort_values('overall_rating').tail(10)

,id,player_fifa_api_id,date,overall_rating,potential,preferred_foot,attacking_work_rate,defensive_work_rate,crossing,finishing,...,vision,penalties,marking,standing_tackle,sliding_tackle,gk_diving,gk_handling,gk_kicking,gk_positioning,gk_reflexes
player_api_id,,,,,,,,,,,,,,,,,,,,,
30613,27351,162895,2011-08-30,88.0,90.0,right,high,medium,83.0,78.0,...,93.0,86.0,62.0,70.0,65.0,6.0,10.0,8.0,15.0,15.0
30878,179289,139869,2011-08-30,88.0,90.0,right,high,medium,84.0,63.0,...,90.0,80.0,48.0,63.0,64.0,9.0,5.0,13.0,11.0,12.0
30657,72604,5479,2011-08-30,89.0,92.0,left,medium,medium,13.0,9.0,...,44.0,24.0,11.0,11.0,9.0,91.0,83.0,69.0,87.0,93.0
30865,131144,140601,2011-08-30,89.0,91.0,right,medium,high,40.0,37.0,...,56.0,62.0,91.0,94.0,86.0,12.0,5.0,14.0,8.0,6.0
30829,178969,54050,2011-08-30,90.0,92.0,right,high,high,79.0,91.0,...,88.0,86.0,32.0,54.0,37.0,10.0,11.0,13.0,8.0,7.0
30834,16477,9014,2011-08-30,90.0,91.0,left,high,low,85.0,84.0,...,86.0,83.0,29.0,24.0,25.0,10.0,8.0,11.0,5.0,15.0
30955,12790,41,2011-08-30,91.0,93.0,right,high,medium,85.0,74.0,...,93.0,65.0,57.0,57.0,56.0,6.0,13.0,6.0,13.0,7.0
39854,180724,10535,2011-08-30,92.0,92.0,right,medium,medium,85.0,70.0,...,97.0,75.0,55.0,62.0,61.0,5.0,15.0,12.0,5.0,9.0
30893,33347,20801,2011-08-30,92.0,94.0,right,high,low,84.0,90.0,...,81.0,87.0,22.0,31.0,23.0,7.0,11.0,15.0,14.0,11.0
30981,102500,158023,2011-08-30,94.0,96.0,left,high,medium,85.0,92.0,...,90.0,86.0,13.0,21.0,20.0,6.0,11.0,15.0,14.0,8.0

In [30]:
df_comb_player_2010 = df_comb_player[df_comb_player['date'].dt.year == 2010]
df_comb_player_2010 = df_comb_player_2010.sort_values('date').groupby('player_api_id').last()
df_comb_player_2010.sort_values('overall_rating').tail(10)

,id,player_fifa_api_id,date,overall_rating,potential,preferred_foot,attacking_work_rate,defensive_work_rate,crossing,finishing,...,vision,penalties,marking,standing_tackle,sliding_tackle,gk_diving,gk_handling,gk_kicking,gk_positioning,gk_reflexes
player_api_id,,,,,,,,,,,,,,,,,,,,,
38460,43933,49072,2010-08-30,87.0,88.0,right,high,medium,73.0,93.0,...,83.0,82.0,22.0,18.0,18.0,8.0,12.0,9.0,5.0,8.0
30631,59274,5471,2010-08-30,87.0,88.0,right,high,medium,82.0,90.0,...,89.0,89.0,53.0,63.0,64.0,12.0,14.0,15.0,10.0,8.0
39854,180726,10535,2010-08-30,87.0,90.0,right,medium,medium,91.0,74.0,...,96.0,81.0,59.0,68.0,67.0,5.0,15.0,12.0,5.0,9.0
30661,25481,13038,2010-08-30,87.0,90.0,right,medium,high,62.0,37.0,...,73.0,58.0,91.0,91.0,92.0,13.0,8.0,14.0,10.0,9.0
30829,178971,54050,2010-08-30,88.0,91.0,right,high,high,80.0,92.0,...,88.0,86.0,53.0,54.0,41.0,10.0,11.0,13.0,8.0,7.0
30909,40717,113422,2010-08-30,88.0,92.0,right,high,medium,79.0,94.0,...,86.0,92.0,22.0,28.0,38.0,8.0,9.0,9.0,11.0,9.0
30822,43446,31432,2010-08-30,88.0,90.0,right,high,high,78.0,93.0,...,79.0,86.0,22.0,32.0,29.0,10.0,11.0,8.0,6.0,14.0
30657,72606,5479,2010-08-30,89.0,92.0,left,medium,medium,13.0,10.0,...,51.0,24.0,11.0,11.0,9.0,93.0,87.0,71.0,89.0,94.0
30893,33349,20801,2010-08-30,89.0,94.0,right,high,low,84.0,89.0,...,80.0,82.0,22.0,31.0,23.0,7.0,11.0,15.0,14.0,11.0
30981,102502,158023,2010-08-30,90.0,95.0,left,high,medium,85.0,91.0,...,91.0,86.0,13.0,21.0,20.0,6.0,11.0,15.0,14.0,8.0

In [31]:
df_comb_player_2009 = df_comb_player[df_comb_player['date'].dt.year == 2009]
df_comb_player_2009 = df_comb_player_2009.sort_values('date').groupby('player_api_id').last()
df_comb_player_2009.sort_values('overall_rating').tail(10)

,id,player_fifa_api_id,date,overall_rating,potential,preferred_foot,attacking_work_rate,defensive_work_rate,crossing,finishing,...,vision,penalties,marking,standing_tackle,sliding_tackle,gk_diving,gk_handling,gk_kicking,gk_positioning,gk_reflexes
player_api_id,,,,,,,,,,,,,,,,,,,,,
41044,92759,138449,2009-08-30,88.0,92.0,right,high,low,83.0,88.0,...,87.0,92.0,22.0,22.0,21.0,4.0,22.0,79.0,22.0,22.0
30717,63872,1179,2009-08-30,88.0,92.0,right,medium,medium,21.0,21.0,...,70.0,85.0,21.0,21.0,9.0,89.0,88.0,75.0,93.0,90.0
30865,131148,140601,2009-08-30,88.0,90.0,right,medium,high,40.0,41.0,...,63.0,78.0,88.0,95.0,85.0,10.0,23.0,62.0,23.0,23.0
35724,183688,41236,2009-08-30,88.0,91.0,right,medium,low,75.0,89.0,...,80.0,91.0,24.0,49.0,28.0,12.0,24.0,69.0,24.0,24.0
30924,58711,156616,2009-08-30,88.0,92.0,right,high,low,87.0,81.0,...,85.0,84.0,20.0,25.0,26.0,7.0,20.0,73.0,20.0,20.0
30618,167136,13743,2009-08-30,88.0,91.0,right,high,high,92.0,84.0,...,86.0,90.0,64.0,76.0,71.0,5.0,23.0,94.0,23.0,23.0
30893,33351,20801,2009-08-30,89.0,94.0,right,high,low,86.0,90.0,...,80.0,86.0,22.0,31.0,23.0,9.0,21.0,71.0,21.0,21.0
30989,92070,48717,2009-08-30,89.0,90.0,left,medium,medium,20.0,20.0,...,63.0,83.0,23.0,20.0,16.0,91.0,89.0,75.0,91.0,92.0
30981,102504,158023,2009-08-30,90.0,95.0,left,high,medium,82.0,90.0,...,91.0,91.0,20.0,21.0,20.0,8.0,20.0,75.0,20.0,20.0
30657,72608,5479,2009-08-30,90.0,92.0,left,medium,medium,22.0,22.0,...,51.0,94.0,22.0,22.0,9.0,93.0,87.0,74.0,91.0,94.0

In [32]:
df_comb_player_2008 = df_comb_player[df_comb_player['date'].dt.year == 2008]
df_comb_player_2008 = df_comb_player_2008.sort_values('date').groupby('player_api_id').last()
df_comb_player_2008.sort_values('overall_rating').tail(10)

,id,player_fifa_api_id,date,overall_rating,potential,preferred_foot,attacking_work_rate,defensive_work_rate,crossing,finishing,...,vision,penalties,marking,standing_tackle,sliding_tackle,gk_diving,gk_handling,gk_kicking,gk_positioning,gk_reflexes
player_api_id,,,,,,,,,,,,,,,,,,,,,
30853,55891,49369,2008-08-30,88.0,90.0,right,high,low,69.0,95.0,...,81.0,89.0,21.0,20.0,29.0,10.0,20.0,51.0,20.0,20.0
30613,27357,162895,2008-08-30,88.0,91.0,right,high,medium,87.0,77.0,...,93.0,94.0,62.0,77.0,68.0,8.0,21.0,95.0,21.0,21.0
30723,6531,1088,2008-08-30,88.0,91.0,right,medium,high,36.0,21.0,...,76.0,92.0,94.0,93.0,87.0,7.0,21.0,66.0,21.0,21.0
30859,142888,48940,2008-08-30,88.0,91.0,left,medium,medium,20.0,20.0,...,45.0,27.0,20.0,20.0,12.0,94.0,91.0,79.0,85.0,90.0
35724,183690,41236,2008-08-30,89.0,94.0,right,medium,low,68.0,93.0,...,80.0,91.0,24.0,69.0,28.0,12.0,24.0,65.0,24.0,24.0
30981,102506,158023,2008-08-30,90.0,95.0,left,high,medium,81.0,87.0,...,91.0,89.0,20.0,25.0,20.0,8.0,20.0,79.0,20.0,20.0
41044,92761,138449,2008-08-30,90.0,93.0,right,high,low,79.0,92.0,...,87.0,92.0,22.0,29.0,21.0,4.0,22.0,79.0,22.0,22.0
30717,63874,1179,2008-08-30,90.0,93.0,right,medium,medium,21.0,21.0,...,70.0,85.0,21.0,21.0,9.0,90.0,92.0,82.0,94.0,91.0
30657,72610,5479,2008-08-30,91.0,92.0,left,medium,medium,22.0,22.0,...,51.0,94.0,22.0,22.0,9.0,94.0,88.0,71.0,90.0,96.0
30893,33353,20801,2008-08-30,91.0,94.0,right,high,low,89.0,92.0,...,80.0,78.0,27.0,35.0,23.0,9.0,21.0,72.0,21.0,21.0

In [33]:
df_comb_player_2007 = df_comb_player[df_comb_player['date'].dt.year == 2007]
df_comb_player_2007 = df_comb_player_2007.sort_values('date').groupby('player_api_id').last()
df_comb_player_2007.sort_values('overall_rating').tail(10)

,id,player_fifa_api_id,date,overall_rating,potential,preferred_foot,attacking_work_rate,defensive_work_rate,crossing,finishing,...,vision,penalties,marking,standing_tackle,sliding_tackle,gk_diving,gk_handling,gk_kicking,gk_positioning,gk_reflexes
player_api_id,,,,,,,,,,,,,,,,,,,,,
38843,183486,28765,2007-08-30,89.0,88.0,left,medium,medium,90.0,40.0,...,91.0,79.0,73.0,78.0,84.0,7.0,22.0,55.0,22.0,22.0
30859,142889,48940,2007-08-30,89.0,91.0,left,medium,medium,20.0,20.0,...,45.0,77.0,20.0,28.0,12.0,91.0,90.0,84.0,88.0,92.0
30829,178975,54050,2007-08-30,90.0,91.0,right,high,high,77.0,90.0,...,88.0,86.0,28.0,42.0,41.0,11.0,21.0,72.0,21.0,21.0
41044,92762,138449,2007-08-30,90.0,91.0,right,high,low,87.0,90.0,...,87.0,77.0,22.0,29.0,21.0,4.0,22.0,90.0,22.0,22.0
30627,84855,13732,2007-08-30,90.0,91.0,right,medium,high,41.0,36.0,...,63.0,85.0,92.0,93.0,87.0,7.0,23.0,61.0,23.0,23.0
30717,63875,1179,2007-08-30,91.0,93.0,right,medium,medium,21.0,21.0,...,70.0,88.0,21.0,21.0,9.0,90.0,91.0,79.0,96.0,90.0
30723,6532,1088,2007-08-30,91.0,92.0,right,medium,high,42.0,24.0,...,76.0,92.0,93.0,95.0,87.0,7.0,21.0,34.0,21.0,21.0
30626,170037,1625,2007-08-30,91.0,91.0,right,medium,low,76.0,95.0,...,82.0,92.0,21.0,21.0,14.0,14.0,21.0,67.0,21.0,21.0
30743,153453,28130,2007-08-30,91.0,93.0,right,medium,low,83.0,90.0,...,92.0,83.0,22.0,28.0,19.0,12.0,22.0,85.0,22.0,22.0
30893,33354,20801,2007-08-30,91.0,94.0,right,high,low,88.0,85.0,...,80.0,79.0,27.0,27.0,23.0,9.0,21.0,73.0,21.0,21.0

# Finding Top Teams

## League Teams

In [34]:
df_comb_team = pd.merge(df_team, df_team_attributes, on="team_api_id")
df_comb_team.head()

,id_x,team_api_id,team_fifa_api_id_x,team_long_name,team_short_name,id_y,team_fifa_api_id_y,date,buildUpPlaySpeed,buildUpPlaySpeedClass,...,chanceCreationShooting,chanceCreationShootingClass,chanceCreationPositioningClass,defencePressure,defencePressureClass,defenceAggression,defenceAggressionClass,defenceTeamWidth,defenceTeamWidthClass,defenceDefenderLineClass
0,1,9987,673.0,KRC Genk,GEN,485,673,2010-02-22 00:00:00,45,Balanced,...,60,Normal,Organised,70,High,65,Press,70,Wide,Cover
1,1,9987,673.0,KRC Genk,GEN,486,673,2011-02-22 00:00:00,66,Balanced,...,51,Normal,Organised,48,Medium,47,Press,54,Normal,Offside Trap
2,1,9987,673.0,KRC Genk,GEN,487,673,2012-02-22 00:00:00,53,Balanced,...,56,Normal,Organised,47,Medium,45,Press,55,Normal,Cover
3,1,9987,673.0,KRC Genk,GEN,488,673,2013-09-20 00:00:00,58,Balanced,...,56,Normal,Organised,47,Medium,45,Press,55,Normal,Cover
4,1,9987,673.0,KRC Genk,GEN,489,673,2014-09-19 00:00:00,58,Balanced,...,56,Normal,Organised,47,Medium,45,Press,55,Normal,Cover

In [35]:
import datetime as dt
df_comb_team['date'] = pd.to_datetime(df_comb_team['date'])

In [38]:
df_comb_team_2015 = df_comb_team[df_comb_team['date'].dt.year == 2015]
df_comb_team_2015 = df_comb_team_2015.sort_values('date').groupby('team_api_id').last()

,id_x,team_fifa_api_id_x,team_long_name,team_short_name,id_y,team_fifa_api_id_y,date,buildUpPlaySpeed,buildUpPlaySpeedClass,buildUpPlayDribbling,...,chanceCreationShooting,chanceCreationShootingClass,chanceCreationPositioningClass,defencePressure,defencePressureClass,defenceAggression,defenceAggressionClass,defenceTeamWidth,defenceTeamWidthClass,defenceDefenderLineClass
team_api_id,,,,,,,,,,,,,,,,,,,,,
1601,31446,874.0,Ruch ChorzÃ³w,CHO,1118,874,2015-09-10,47,Balanced,48.0,...,50,Normal,Organised,43,Medium,44,Press,49,Normal,Cover
1957,31456,110745.0,Jagiellonia BiaÅ‚ystok,BIA,624,110745,2015-09-10,66,Balanced,54.0,...,66,Normal,Organised,57,Medium,56,Press,49,Normal,Cover
2182,31453,873.0,Lech PoznaÅ„,POZ,700,873,2015-09-10,57,Balanced,50.0,...,67,Lots,Free Form,50,Medium,58,Press,45,Normal,Cover
2186,31458,110747.0,Cracovia,CKR,335,110747,2015-09-10,37,Balanced,50.0,...,33,Little,Organised,59,Medium,34,Press,64,Normal,Cover
4087,11822,111271.0,Ã‰vian Thonon Gaillard FC,ETG,415,111271,2015-09-10,58,Balanced,35.0,...,51,Normal,Organised,47,Medium,43,Press,50,Normal,Cover

In [41]:
df_match.head()

,id,country_id,league_id,season,stage,date,match_api_id,home_team_api_id,away_team_api_id,home_team_goal,...,SJA,VCH,VCD,VCA,GBH,GBD,GBA,BSH,BSD,BSA
0,1,1,1,2008/2009,1,2008-08-17 00:00:00,492473,9987,9993,1,...,4.00,1.65,3.40,4.50,1.78,3.25,4.00,1.73,3.40,4.20
1,2,1,1,2008/2009,1,2008-08-16 00:00:00,492474,10000,9994,0,...,3.80,2.00,3.25,3.25,1.85,3.25,3.75,1.91,3.25,3.60
2,3,1,1,2008/2009,1,2008-08-16 00:00:00,492475,9984,8635,0,...,2.50,2.35,3.25,2.65,2.50,3.20,2.50,2.30,3.20,2.75
3,4,1,1,2008/2009,1,2008-08-17 00:00:00,492476,9991,9998,5,...,7.50,1.45,3.75,6.50,1.50,3.75,5.50,1.44,3.75,6.50
4,5,1,1,2008/2009,1,2008-08-16 00:00:00,492477,7947,9985,1,...,1.73,4.50,3.40,1.65,4.50,3.50,1.65,4.75,3.30,1.67

In [83]:
df_match['date'] = pd.to_datetime(df_match['date'])

In [84]:
print(df_match.columns[0:25])

Index(['id', 'country_id', 'league_id', 'season', 'stage', 'date',
       'match_api_id', 'home_team_api_id', 'away_team_api_id',
       'home_team_goal', 'away_team_goal', 'home_player_X1', 'home_player_X2',
       'home_player_X3', 'home_player_X4', 'home_player_X5', 'home_player_X6',
       'home_player_X7', 'home_player_X8', 'home_player_X9', 'home_player_X10',
       'home_player_X11', 'away_player_X1', 'away_player_X2',
       'away_player_X3'],
      dtype='object')

In [85]:
print(df_match.columns[50:])

Index(['away_player_Y7', 'away_player_Y8', 'away_player_Y9', 'away_player_Y10',
       'away_player_Y11', 'home_player_1', 'home_player_2', 'home_player_3',
       'home_player_4', 'home_player_5', 'home_player_6', 'home_player_7',
       'home_player_8', 'home_player_9', 'home_player_10', 'home_player_11',
       'away_player_1', 'away_player_2', 'away_player_3', 'away_player_4',
       'away_player_5', 'away_player_6', 'away_player_7', 'away_player_8',
       'away_player_9', 'away_player_10', 'away_player_11', 'goal', 'shoton',
       'shotoff', 'foulcommit', 'card', 'cross', 'corner', 'possession',
       'B365H', 'B365D', 'B365A', 'BWH', 'BWD', 'BWA', 'IWH', 'IWD', 'IWA',
       'LBH', 'LBD', 'LBA', 'PSH', 'PSD', 'PSA', 'WHH', 'WHD', 'WHA', 'SJH',
       'SJD', 'SJA', 'VCH', 'VCD', 'VCA', 'GBH', 'GBD', 'GBA', 'BSH', 'BSD',
       'BSA'],
      dtype='object')

In [246]:
df_match_2015 = df_match[df_match.season=="2015/2016"]
df_match_2014 = df_match[df_match.season=="2014/2015"]
df_match_2013 = df_match[df_match.season=="2013/2014"]
df_match_2012 = df_match[df_match.season=="2012/2013"]
df_match_2011 = df_match[df_match.season=="2011/2012"]
df_match_2010 = df_match[df_match.season=="2010/2011"]
df_match_2009 = df_match[df_match.season=="2009/2010"]

In [247]:
players_list_home = ['home_team_api_id','home_player_1', 'home_player_2', 'home_player_3',
       'home_player_4', 'home_player_5', 'home_player_6', 'home_player_7',
       'home_player_8', 'home_player_9', 'home_player_10', 'home_player_11']

In [248]:
df_team_to_player_2015 = df_match_2015[players_list_home]

In [249]:
df_team_to_player_2015.head()

,home_team_api_id,home_player_1,home_player_2,home_player_3,home_player_4,home_player_5,home_player_6,home_player_7,home_player_8,home_player_9,home_player_10,home_player_11
1488,9997,242243.0,130738.0,164323.0,210392.0,466480.0,641042.0,613260.0,215415.0,207603.0,466589.0,365245.0
1489,8571,206592.0,94284.0,156693.0,157375.0,181312.0,95614.0,192326.0,38257.0,478447.0,70959.0,581141.0
1490,9987,91929.0,465750.0,195448.0,149219.0,166675.0,533228.0,37112.0,32863.0,38969.0,354494.0,25957.0
1491,8573,107806.0,95615.0,298941.0,30918.0,173462.0,201811.0,208985.0,38365.0,265123.0,166302.0,206182.0
1492,10000,37900.0,289883.0,563215.0,46232.0,303179.0,298665.0,26916.0,26613.0,38262.0,431589.0,46335.0

In [250]:
list_of_team_id = df_team_to_player_2015.home_team_api_id.unique().tolist()

In [251]:
team_dict = {}

In [252]:
for team_name in list_of_team_id:
    df = df_team_to_player_2015[df_team_to_player_2015.home_team_api_id== team_name]
    for player_name in pd.Series(df.values.ravel('F')).unique():
        team_dict[player_name]=team_name

In [258]:
df_player_team_2015 = pd.DataFrame(team_dict,index=[0])
df_player_team_2015=df_player_team_2015.T
df_player_team_2015.reset_index(level=0, inplace=True)
df_player_team_2015.rename(index=str, columns={"index": "player_api_id", 0: "team_api_id"},inplace=True)
df_player_team_2015.head()

   player_api_id  team_api_id
0         9997.0         9997
1       242243.0         9997
2        38341.0         9997
3       130738.0         9997
4       561611.0         9997

In [259]:
df_player_team_2015 = pd.merge(df_player_team_2015,df_comb_player_2015,on="player_api_id")
df_player_team_2015 = pd.merge(df_player_team_2015,df_team,on="team_api_id")

In [261]:
df_player_team_2015.head()

,player_api_id,team_api_id,id_x,player_fifa_api_id,date,overall_rating,potential,preferred_foot,attacking_work_rate,defensive_work_rate,...,sliding_tackle,gk_diving,gk_handling,gk_kicking,gk_positioning,gk_reflexes,id_y,team_fifa_api_id,team_long_name,team_short_name
0,242243.0,9997,179741,212632,2015-12-17,69.0,70.0,right,medium,medium,...,16.0,72.0,67.0,64.0,69.0,75.0,614,680.0,Sint-Truidense VV,STT
1,38341.0,9997,182859,177815,2015-11-19,65.0,65.0,right,medium,medium,...,20.0,68.0,64.0,56.0,66.0,65.0,614,680.0,Sint-Truidense VV,STT
2,130738.0,9997,108174,229641,2015-09-21,65.0,67.0,right,high,medium,...,70.0,7.0,12.0,8.0,6.0,9.0,614,680.0,Sint-Truidense VV,STT
3,561611.0,9997,60890,228353,2015-12-17,63.0,73.0,right,high,high,...,45.0,11.0,12.0,12.0,8.0,14.0,614,680.0,Sint-Truidense VV,STT
4,179365.0,9997,121667,194190,2015-11-26,71.0,73.0,right,high,high,...,63.0,16.0,9.0,13.0,11.0,13.0,614,680.0,Sint-Truidense VV,STT

In [267]:
df_player_team_2015 = df_player_team_2015.drop(['preferred_foot', 'attacking_work_rate',
       'defensive_work_rate', 'crossing', 'finishing', 'heading_accuracy',
       'short_passing', 'volleys', 'dribbling', 'curve', 'free_kick_accuracy',
       'long_passing', 'ball_control', 'acceleration', 'sprint_speed',
       'agility', 'reactions', 'balance', 'shot_power', 'jumping', 'stamina',
       'strength', 'long_shots', 'aggression', 'interceptions', 'positioning',
       'vision', 'penalties', 'marking', 'standing_tackle', 'sliding_tackle',  'team_short_name','id_y','date','id_x'],axis=1)

In [268]:
df_player_team_2015.head()

,player_api_id,team_api_id,player_fifa_api_id,overall_rating,potential,gk_diving,gk_handling,gk_kicking,gk_positioning,gk_reflexes,team_fifa_api_id,team_long_name
0,242243.0,9997,212632,69.0,70.0,72.0,67.0,64.0,69.0,75.0,680.0,Sint-Truidense VV
1,38341.0,9997,177815,65.0,65.0,68.0,64.0,56.0,66.0,65.0,680.0,Sint-Truidense VV
2,130738.0,9997,229641,65.0,67.0,7.0,12.0,8.0,6.0,9.0,680.0,Sint-Truidense VV
3,561611.0,9997,228353,63.0,73.0,11.0,12.0,12.0,8.0,14.0,680.0,Sint-Truidense VV
4,179365.0,9997,194190,71.0,73.0,16.0,9.0,13.0,11.0,13.0,680.0,Sint-Truidense VV

In [273]:
df_team_performance_2015 = df_player_team_2015.groupby("team_api_id").sum()["overall_rating"]

In [275]:
df_team_performance_2015.sort_values("overall_rating")

TypeError: sort_values() got multiple values for argument 'axis'

In [214]:
df_player_team

,player_api_id,team_api_id,id_x,player_fifa_api_id,date,overall_rating,potential,preferred_foot,attacking_work_rate,defensive_work_rate,...,sliding_tackle,gk_diving,gk_handling,gk_kicking,gk_positioning,gk_reflexes,id_y,team_fifa_api_id,team_long_name,team_short_name
0,242243.0,9997,179740,212632,2016-02-04,70.0,71.0,right,medium,medium,...,16.0,73.0,67.0,64.0,69.0,75.0,614,680.0,Sint-Truidense VV,STT
1,242243.0,9997,179741,212632,2015-12-17,69.0,70.0,right,medium,medium,...,16.0,72.0,67.0,64.0,69.0,75.0,614,680.0,Sint-Truidense VV,STT
2,242243.0,9997,179742,212632,2015-12-03,69.0,70.0,right,medium,medium,...,16.0,72.0,67.0,64.0,69.0,75.0,614,680.0,Sint-Truidense VV,STT
3,242243.0,9997,179743,212632,2015-11-26,69.0,71.0,right,medium,medium,...,16.0,72.0,67.0,64.0,69.0,75.0,614,680.0,Sint-Truidense VV,STT
4,242243.0,9997,179744,212632,2015-11-19,69.0,70.0,right,medium,medium,...,16.0,72.0,67.0,64.0,69.0,75.0,614,680.0,Sint-Truidense VV,STT
5,242243.0,9997,179745,212632,2015-11-06,66.0,67.0,right,medium,medium,...,16.0,69.0,65.0,61.0,67.0,71.0,614,680.0,Sint-Truidense VV,STT
6,242243.0,9997,179746,212632,2015-09-21,66.0,68.0,right,medium,medium,...,16.0,69.0,65.0,61.0,67.0,71.0,614,680.0,Sint-Truidense VV,STT
7,242243.0,9997,179747,212632,2007-02-22,66.0,68.0,right,medium,medium,...,16.0,69.0,65.0,61.0,67.0,71.0,614,680.0,Sint-Truidense VV,STT
8,38341.0,9997,182858,177815,2016-04-28,65.0,65.0,right,medium,medium,...,20.0,68.0,64.0,56.0,66.0,65.0,614,680.0,Sint-Truidense VV,STT
9,38341.0,9997,182859,177815,2015-11-19,65.0,65.0,right,medium,medium,...,20.0,68.0,64.0,56.0,66.0,65.0,614,680.0,Sint-Truidense VV,STT
10,38341.0,9997,182860,177815,2015-09-21,66.0,66.0,right,medium,medium,...,20.0,69.0,64.0,56.0,66.0,66.0,614,680.0,Sint-Truidense VV,STT
11,38341.0,9997,182861,177815,2015-05-08,66.0,67.0,right,medium,medium,...,25.0,70.0,63.0,59.0,65.0,68.0,614,680.0,Sint-Truidense VV,STT
12,38341.0,9997,182862,177815,2014-11-07,66.0,68.0,right,medium,medium,...,25.0,70.0,63.0,59.0,65.0,68.0,614,680.0,Sint-Truidense VV,STT
13,38341.0,9997,182863,177815,2014-09-18,67.0,68.0,right,medium,medium,...,25.0,71.0,65.0,60.0,66.0,69.0,614,680.0,Sint-Truidense VV,STT
14,38341.0,9997,182864,177815,2013-12-20,68.0,68.0,right,medium,medium,...,25.0,72.0,66.0,61.0,67.0,70.0,614,680.0,Sint-Truidense VV,STT
15,38341.0,9997,182865,177815,2013-10-18,68.0,69.0,right,medium,medium,...,25.0,71.0,66.0,61.0,67.0,71.0,614,680.0,Sint-Truidense VV,STT
16,38341.0,9997,182866,177815,2013-09-20,68.0,71.0,right,medium,medium,...,25.0,71.0,66.0,61.0,67.0,71.0,614,680.0,Sint-Truidense VV,STT
17,38341.0,9997,182867,177815,2013-04-19,68.0,71.0,right,medium,medium,...,19.0,71.0,66.0,61.0,67.0,71.0,614,680.0,Sint-Truidense VV,STT
18,38341.0,9997,182868,177815,2012-08-31,68.0,71.0,right,medium,medium,...,19.0,71.0,66.0,61.0,67.0,71.0,614,680.0,Sint-Truidense VV,STT
19,38341.0,9997,182869,177815,2012-02-22,68.0,72.0,right,medium,medium,...,19.0,71.0,66.0,61.0,67.0,71.0,614,680.0,Sint-Truidense VV,STT
20,38341.0,9997,182870,177815,2011-08-30,68.0,72.0,right,medium,medium,...,19.0,70.0,66.0,61.0,67.0,71.0,614,680.0,Sint-Truidense VV,STT
21,38341.0,9997,182871,177815,2011-02-22,68.0,74.0,right,medium,medium,...,19.0,70.0,66.0,65.0,67.0,71.0,614,680.0,Sint-Truidense VV,STT
22,38341.0,9997,182872,177815,2010-08-30,68.0,74.0,right,medium,medium,...,19.0,70.0,66.0,65.0,67.0,71.0,614,680.0,Sint-Truidense VV,STT
23,38341.0,9997,182873,177815,2010-02-22,67.0,73.0,right,medium,medium,...,19.0,67.0,64.0,63.0,67.0,71.0,614,680.0,Sint-Truidense VV,STT
24,38341.0,9997,182874,177815,2009-08-30,67.0,73.0,right,medium,medium,...,19.0,67.0,64.0,63.0,67.0,71.0,614,680.0,Sint-Truidense VV,STT
25,38341.0,9997,182875,177815,2008-08-30,64.0,73.0,right,medium,medium,...,19.0,64.0,63.0,62.0,62.0,67.0,614,680.0,Sint-Truidense VV,STT
26,38341.0,9997,182876,177815,2007-08-30,60.0,73.0,right,medium,medium,...,19.0,64.0,63.0,58.0,56.0,59.0,614,680.0,Sint-Truidense VV,STT
27,38341.0,9997,182877,177815,2007-02-22,60.0,73.0,right,medium,medium,...,19.0,64.0,63.0,58.0,56.0,59.0,614,680.0,Sint-Truidense VV,STT
28,130738.0,9997,108171,229641,2016-04-28,66.0,67.0,right,high,medium,...,70.0,7.0,12.0,8.0,6.0,9.0,614,680.0,Sint-Truidense VV,STT
29,130738.0,9997,108172,229641,2016-02-04,66.0,67.0,right,high,medium,...,70.0,7.0,12.0,8.0,6.0,9.0,614,680.0,Sint-Truidense VV,STT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
87140,140490.0,7896,119546,203439,2016-02-18,59.0,65.0,right,medium,medium,...,21.0,6.0,7.0,14.0,10.0,9.0,51606,NaN,Lugano,LUG
87141,140490.0,7896,119547,203439,2016-01-07,59.0,66.0,right,medium,medium,...,21.0,6.0,7.0,14.0,10.0,9.0,51606,NaN,Lugano,LUG
87142,140490.0,7896,119548,203439,2015-10-02,59.0,66.0,right,medium,medium,...,21.0,6.0,7.0,14.0,10.0,9.0,51606,NaN,Lugano,LUG
87143,140490.0,7896,119549,203439,2015-09-21,59.0,66.0,right,medium,medium,...,21.0,6.0,7.0,14.0,10.0,9.0,51606,NaN,Lugano,LUG
87144,140490.0,7896,119550,203439,2014-10-10,59.0,66.0,right,medium,medium,...,21.0,6.0,7.0,14.0,10.0,9.0,51606,NaN,Lugano,LUG
87145,140490.0,7896,119551,203439,2014-09-18,59.0,66.0,right,medium,medium,...,21.0,6.0,7.0,14.0,10.0,9.0,51606,NaN,Lugano,LUG
87146,140490.0,7896,119552,203439,2012-02-22,59.0,66.0,right,medium,medium,...,21.0,6.0,7.0,14.0,10.0,9.0,51606,NaN,Lugano,LUG
87147,140490.0,7896,119553,203439,2011-08-30,59.0,66.0,right,medium,medium,...,21.0,6.0,7.0,14.0,10.0,9.0,51606,NaN,Lugano,LUG
87148,140490.0,7896,119554,203439,2007-02-22,59.0,66.0,right,medium,medium,...,21.0,6.0,7.0,14.0,10.0,9.0,51606,NaN,Lugano,LUG
87149,93229.0,7896,139659,170742,2015-11-12,59.0,60.0,left,medium,low,...,22.0,7.0,8.0,8.0,11.0,13.0,51606,NaN,Lugano,LUG
87150,93229.0,7896,139660,170742,2015-11-06,57.0,58.0,left,medium,low,...,22.0,7.0,8.0,8.0,11.0,13.0,51606,NaN,Lugano,LUG
87151,93229.0,7896,139661,170742,2015-10-09,57.0,59.0,left,medium,low,...,22.0,7.0,8.0,8.0,11.0,13.0,51606,NaN,Lugano,LUG
87152,93229.0,7896,139662,170742,2015-09-21,57.0,60.0,left,medium,low,...,22.0,7.0,8.0,8.0,11.0,13.0,51606,NaN,Lugano,LUG
87153,93229.0,7896,139663,170742,2014-11-07,57.0,60.0,left,medium,low,...,22.0,7.0,8.0,8.0,11.0,13.0,51606,NaN,Lugano,LUG
87154,93229.0,7896,139664,170742,2014-10-31,57.0,60.0,left,medium,low,...,43.0,7.0,8.0,8.0,11.0,13.0,51606,NaN,Lugano,LUG
87155,93229.0,7896,139665,170742,2014-10-02,49.0,60.0,left,medium,low,...,43.0,7.0,8.0,8.0,11.0,13.0,51606,NaN,Lugano,LUG
87156,93229.0,7896,139666,170742,2014-09-18,50.0,60.0,left,medium,low,...,43.0,7.0,8.0,8.0,11.0,13.0,51606,NaN,Lugano,LUG
87157,93229.0,7896,139667,170742,2007-02-22,50.0,60.0,left,medium,low,...,43.0,7.0,8.0,8.0,11.0,13.0,51606,NaN,Lugano,LUG
87158,198500.0,7896,45451,229846,2016-02-18,55.0,61.0,right,high,low,...,18.0,6.0,12.0,7.0,7.0,12.0,51606,NaN,Lugano,LUG
87159,198500.0,7896,45452,229846,2015-11-12,55.0,62.0,right,high,low,...,18.0,6.0,12.0,7.0,7.0,12.0,51606,NaN,Lugano,LUG
87160,198500.0,7896,45453,229846,2015-09-21,55.0,62.0,right,high,low,...,18.0,6.0,12.0,7.0,7.0,12.0,51606,NaN,Lugano,LUG
87161,198500.0,7896,45454,229846,2007-02-22,55.0,62.0,right,high,low,...,18.0,6.0,12.0,7.0,7.0,12.0,51606,NaN,Lugano,LUG
87162,178142.0,7896,120215,176246,2016-06-02,62.0,66.0,right,medium,low,...,36.0,6.0,12.0,7.0,7.0,14.0,51606,NaN,Lugano,LUG
87163,178142.0,7896,120216,176246,2016-02-18,62.0,67.0,right,medium,low,...,36.0,6.0,12.0,7.0,7.0,14.0,51606,NaN,Lugano,LUG
87164,178142.0,7896,120217,176246,2015-10-30,62.0,67.0,right,medium,low,...,36.0,6.0,12.0,7.0,7.0,14.0,51606,NaN,Lugano,LUG
87165,178142.0,7896,120218,176246,2015-10-23,62.0,67.0,right,medium,low,...,36.0,6.0,12.0,7.0,7.0,14.0,51606,NaN,Lugano,LUG
87166,178142.0,7896,120219,176246,2015-10-02,61.0,66.0,right,medium,low,...,36.0,6.0,12.0,7.0,7.0,14.0,51606,NaN,Lugano,LUG
87167,178142.0,7896,120220,176246,2015-09-21,61.0,66.0,right,high,medium,...,36.0,6.0,12.0,7.0,7.0,14.0,51606,NaN,Lugano,LUG
87168,178142.0,7896,120221,176246,2007-08-30,61.0,66.0,right,high,medium,...,36.0,6.0,12.0,7.0,7.0,14.0,51606,NaN,Lugano,LUG
87169,178142.0,7896,120222,176246,2007-02-22,41.0,66.0,right,high,medium,...,36.0,6.0,7.0,31.0,5.0,6.0,51606,NaN,Lugano,LUG

In [209]:
"""from scipy.stats import zscore

list_of_attributes =  ['buildUpPlaySpeed','buildUpPlayDribbling','buildUpPlayPassing','defenceAggression','chanceCreationPassing','chanceCreationShooting','defencePressure','defenceTeamWidth']
#df_comb_team_2015['rating']=df_comb_team_2015[list_of_attributes].apply(zscore).sum(axis=1)
df_comb_team_2015['rating']=df_comb_team_2015[list_of_attributes].sum(axis=1)"""

"from scipy.stats import zscore\n\nlist_of_attributes =  ['buildUpPlaySpeed','buildUpPlayDribbling','buildUpPlayPassing','defenceAggression','chanceCreationPassing','chanceCreationShooting','defencePressure','defenceTeamWidth']\n#df_comb_team_2015['rating']=df_comb_team_2015[list_of_attributes].apply(zscore).sum(axis=1)\ndf_comb_team_2015['rating']=df_comb_team_2015[list_of_attributes].sum(axis=1)"